nodes:
  # Previous tests
  test_append:
    template: append
    dependencies:
      table_1: test_table_1
      table_2: test_table_2

  test_filter:
    template: filter
    dependencies:
      source_table: test_table_1
      condition: "id = 1"

  test_join:
    template: join
    dependencies:
      left_table: test_table_1
      right_table: test_table_2
      join_type: INNER
      left_key: id
      right_key: id

  # New Alteryx tools for 0.18
  test_sort:
    template: sort
    dependencies:
      source_table: test_table_1
      sort_columns: "name DESC"

  test_union_all:
    template: union_all
    dependencies:
      table_1: test_table_1
      table_2: test_table_1
